### ISSUE TITLE
Update to scala 3?

### ISSUE THREAD

**Issue by jetaggart** [mschuwalow/zio-todo-backend#151]
I've been messing around with trying to upgrade this to scala 3 and have struggled a bit. Have you attempted to update to scala 3 yet or is it impossible right now?

**Comment by mschuwalow** [comment]
I haven't looked at migrating to scala 3 yet.
If you have an almost working version, feel free to open a draft pr and we can try to fix the remaining issues together.

**Comment by psylinse** [comment]
I don't think this is worth it yet. I'll wait 'til 3 is officially released and try again.

**Comment by boggye** [comment]
it's 2023. Scala 3 has been out for a while? Re-open this issue?
