### ISSUE TITLE
Add sbt build

### ISSUE THREAD

**Issue by mschuwalow** [mschuwalow/zio-todo-backend#5]
See #4

**Comment by tampler** [comment]
Added in [my project](https://github.com/Clover-Group/zio_front)

**Comment by mschuwalow** [comment]
Cool. Fine if I use it as base here? I would still need a docker build as that is what i currently use to deploy it. 
Alternatively a pr would obviously be great

**Comment by tampler** [comment]
Sure, go ahead and use it as you wish. There's zero unique code in this project, apart of a small sbt file :).
Pls help me with your failing tests in change

Best,
Boris
